import Header from "@/components/Header";
import "./globals.css";
import { Unbounded, Lexend } from "next/font/google";

const unbounded = Lexend({
  weight: ["400", "700"],
  // preload: false,
  subsets: ["latin"],
  // weight: "700",
  // variable: "--font-poppins",
  // style: ["normal"],
  // display: "swap",
});

export const metadata = {
  title: "Techno Animates",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${unbounded.className} bg-black text-white `}>
        <Header />

        {children}
      </body>
    </html>
  );
}
